### ISSUE TITLE
Calling a service reference in SF5

### ISSUE THREAD

**Issue by ollietb** [ibrahimgunduz34/maria-bundle#9]
Hi there
I'm using Symfony 5 and I've not had any issues so far, but now I'm trying to use a service from the container as a reference for the handler so that I can inject some services, but I'm getting the error `not existing action handler: @badge.handler.keenbean`
Here's what I have in the config
```yaml
maria:
  score_keen_bean:
    trigger: score.updated
    handler: 
      reference: "@badge.handler.keenbean"
      method: onAction
      serialize: true
    rules:
      score_type:   { eql: 'first_to_arrive' }
      total_points: { gt: 100 }
```
And in my services.yaml
```yaml
services:
    badge.handler.keenbean:
      class: 'App\BadgeHandler\KeenBeanHandler'
      arguments: ['@App\Manager\BadgeManager']
```
I'm guessing the issue is with using the new container in Symfony 5? Or is it that I'm using the handler reference wrongly? There isn't an example of it in the README.
Thanks

**Comment by ibrahimgunduz34** [comment]
Hi;
Thank you for your feedback. Apparently, the DI component can't find the reference in the container. You can see clearly from here when the bundle throws the exception 
https://github.com/ibrahimgunduz34/maria-bundle/blob/master/DependencyInjection/MariaExtension.php#L64

I see two possibilities which are listed below but I'll check it anyway:
* services.yaml might not be included. 
* The cached container may not contain the references defined in services.yaml.

Because for both scenarios the container wouldn't contain the reference, you can check the existing services in the container by running the following command before doing anything.

```
 php bin/console debug:container
```
for more details about the command: https://symfony.com/doc/current/service_container/debug.html

For the first scenario, you should ensure that the services.yaml file is included.
For the second scenario, you can simply clear the container cache for the environment that you run the application.

Thanks.
Ibrahim

**Comment by ollietb** [comment]
I did some further investigation into this issue last night. It's not finding the service because the bundle Extension is loaded before the rest of the services so it would never find the service during the bundle configuration stage. The only way I could see it working with using a service defined in the user's services.yaml is to fetch the service via a tag in the compiler pass. eg something like this:
```yaml
services:
    badge.handler.keenbean:
      class: 'App\BadgeHandler\KeenBeanHandler'
      arguments: ['@App\Manager\BadgeManager']
      tags:
        - { name: 'maria.handler', scenario: 'score_keen_bean'}
```
However, the reason I was trying to inject a service like this is because the autowiring wasn't working when using a class name in the `handler` parameter of the config. I managed to edit the Extension and added the line 
```php
$definition->setAutowired(true);
```
Which worked for me. I can submit a PR soon.
